### ISSUE TITLE
Support for UTF-8 Identifiers

### ISSUE THREAD

**Issue by Janfel** [MunifTanjim/tree-sitter-lua#13]
LuaJIT supports UTF-8 identifiers, see the `loadfile()` section in https://luajit.org/extensions.html. Some other tools like https://github.com/sumneko/lua-language-server also support this extension. As this grammar is used with LuaJIT in Neovim, please support Unicode identifiers as well.

**Comment by MunifTanjim** [comment]
Could you maybe provide some test cases that are failing? 🤔

**Comment by Janfel** [comment]
I’m not quite sure this is what you were looking for, I’ve never worked on Treesitter grammars before, but take this sample program:

```lua
local æther = 5
local façade = 6
print(æther + façade)
```

This is a valid LuaJIT program that prints `11`, both inside and outside of Neovim. It features non-ASCII letters at the beginning of an identifier (`æther`) and in the middle of an identifier (`façade`).

In Neovim with Treesitter syntax highlighting, the sections marked with `[...]` are currently highlighted as syntax errors.

```lua
local [æ]ther = 5
local fa[ç]ade = 6
print([æ]ther + fa[çade])
```

This is unsurprising, as AFAICT the following line of this grammar is responsible for matching an identifier.

https://github.com/MunifTanjim/tree-sitter-lua/blob/c9ece5b2d348f917052db5a2da9bd4ecff07426c/grammar.js#L485

While searching for the way LuaJIT defines an identifier, I’ve found the following comment in the LuaJIT source code. This comment states that any non-ASCII codepoint may be used in an identifier.

https://github.com/LuaJIT/LuaJIT/blob/dad04f1754723e76ba9dcf9f401f3134a0cd3972/src/lj_char.c#L10-L13

**Comment by MunifTanjim** [comment]
Thanks for bringing this up. The latest [`v0.0.13`](https://github.com/MunifTanjim/tree-sitter-lua/tree/v0.0.13) release should support full range of characters for identifier.
