### ISSUE TITLE
Highlighting lua5.4 <const> and <close> does not work and buga the rest highlighted

### ISSUE THREAD

**Issue by GabrielFrigo4** [MunifTanjim/tree-sitter-lua#15]
Without '\<const\>'
![image](https://user-images.githubusercontent.com/66432268/198904851-aabdddbe-4cfd-4c97-a703-9b6d8de40d06.png)
With '\<const\>'
![image](https://user-images.githubusercontent.com/66432268/198904867-aed68f5a-a907-43c8-8609-db3f13a6499b.png)
What do you have to do to fix this? because I use lua5.4 and I end up using these features
https://lwn.net/Articles/826134/

**Comment by GabrielFrigo4** [comment]
the highlight in the \<const\> remains the same as the image, but no longer spoils the rest of the highlight

**Comment by MunifTanjim** [comment]
Hmm... wait, I haven't merged the change yet 🤔

**Comment by MunifTanjim** [comment]
Should be usable with Neovim once https://github.com/nvim-treesitter/nvim-treesitter/pull/3747 gets merged.
