### ISSUE TITLE
Error executing lua

### ISSUE THREAD

**Issue by Fluued** [MunifTanjim/tree-sitter-lua#17]
I am getting this error:
![image](https://user-images.githubusercontent.com/110692163/204148128-2f004f97-f447-4e8c-a25b-653e00c7f6a5.png)

:healthcheck nvim-treesitter output:
![image](https://user-images.githubusercontent.com/110692163/204148192-4b56a8a7-303f-4d02-b8e3-cf40429c8204.png)

No other languages seem to throw any errors

**Comment by MunifTanjim** [comment]
This is not the right place for this issue. Check here: https://github.com/nvim-treesitter/nvim-treesitter

**Comment by Fluued** [comment]
I have literally disabled all the plugins and it still doesn't work wdym?

**Comment by MunifTanjim** [comment]
Again this repo is just for the parser and not even related to Neovim in any way. You should discuss this issue in https://github.com/nvim-treesitter/nvim-treesitter

**Comment by Fluued** [comment]
oh ok sorry
