### ISSUE TITLE
Comment nodes substituted by string literals by mistake

### ISSUE THREAD

**Issue by ahlinc** [MunifTanjim/tree-sitter-lua#36]
![Screenshot from 2023-07-19 23-03-23](https://github.com/MunifTanjim/tree-sitter-lua/assets/14666676/6f8a7a83-d174-477c-a4c1-8a8227a23b72)

On the left side it's shown how comment nodes look in this grammar implementation, it would be better to represent them by simple non literal nodes like:
```js
    // comment
    comment: ($) =>
      choice(
        seq(
          field('start', '--'), // I removed alias at all, because it's a bad practice to hide actual string literal tokens
          field('content', alias(/[^\r\n]*/, $.comment_content))
        ),
        seq(
          field('start', alias($._block_comment_start, $.comment_start)),
          field(
            'content',
            optional(alias($._block_comment_content, $.comment_content))
          ),
          field('end', alias($._block_comment_end, $.comment_end))
        )
      ),
  },
```

**Comment by MunifTanjim** [comment]
Just curious, does having named node provide any additional benefits here?

You've provided example from https://github.com/tjdevries/tree-sitter-lua, but I see that both parser do the same thing here.

**Comment by MunifTanjim** [comment]
Anyway, I've opened a PR to make `comment` node structured similar to `string` node: https://github.com/MunifTanjim/tree-sitter-lua/pull/37

**Comment by ahlinc** [comment]
> Just curious, does having named node provide any additional benefits here?

It help's to avoid misunderstanding because anonymous nodes usually are used for a language syntax elements like braces, operators and so on.
