### ISSUE TITLE
Wrong definition node of variable appears after inserting a comment to the sequence of assignments

### ISSUE THREAD

**Issue by rosingrind** [MunifTanjim/tree-sitter-lua#38]
## Summary

Suppose you have a file with such layout:

```lua
local opt = vim.opt

opt.signcolumn = "yes:1"
opt.wrap = true
opt.linebreak = true
opt.showbreak = " ↪"
opt.breakindent = true
opt.breakat = " \t;:,!?"
opt.breakindentopt = "min:40,shift:2"
opt.relativenumber = true
opt.showtabline = 2
opt.expandtab = true
opt.smartindent = true
opt.tabstop = 4
opt.shiftwidth = 4
opt.showmode = false
opt.list = true
opt.listchars:append({ lead = " ", eol = "↩", space = "·" })
opt.suffixes:append({ "lock" })
opt.wildignore:append({ "*-lock.json" })
```

I'm using `nvim-treesitter-refactor` to highlight definitions and usages of a node. If you add a comment somewhere in between of opt assignments, you'll get a node pointing to the definition of `local opt` (and you can go there using `gnd` if you're using navigation)

<img width="1142" alt="Screenshot 2023-08-16 at 6 55 54 AM" src="https://github.com/MunifTanjim/tree-sitter-lua/assets/108860307/869a6efe-f29e-41a5-b81c-8ad272e2f1de">

If you'll remove the comment, clear a buffer and paste it again without the comment, you'll get no definitions for `opt` and `gnd` action is obviously not working.

## Info

- Tested both on `v0.9.1` from `brew` and latest [nightly](https://github.com/neovim/neovim/releases/tag/nightly) binary
- macOS Ventura 13.5 (22G74)
- `:TSUpdate lua` returns `Parsers are up-to-date!`

**Comment by MunifTanjim** [comment]
I don't understand the issue. Is the parser not working?

Maybe open an issue on `nvim-treesitter-refactor` repo?

**Comment by rosingrind** [comment]
The parser either parses a misleading definition node, or not parses it at all, so I assume it's not working properly. I don't see a particular reason to open this at the refactor repo as it only grabs a data from parser modules and don't make any additions to ast which may cause this issue, see https://github.com/nvim-treesitter/nvim-treesitter-refactor/blob/65ad2eca822dfaec2a3603119ec3cc8826a7859e/lua/nvim-treesitter-refactor/navigation.lua#L28

> ![260896730-869a6efe-f29e-41a5-b81c-8ad272e2f1de~2](https://github.com/MunifTanjim/tree-sitter-lua/assets/108860307/f725b8d1-7533-46a1-870c-105777b383a4)

It does not make any sense to have a definition node on line 13 or any lines except the one where the variable is defined. It also doesn't when the def node completely vanishes after clearing all comments and re-pasting the same code to clear buffer.

**Comment by MunifTanjim** [comment]
> The parser either parses a misleading definition node, or not parses it at all, so I assume it's not working properly.

Did you run `:InspectTree` and see the generated tree? Otherwise it's just assumption.

I coudln't reproduce any issues with your example.

**Comment by clason** [comment]
> so I assume it's not working properly

Do not assume, check. `tree-sitter-refactor` makes use of `locals` queries, which are managed by `nvim-treesitter`. These could very well be faulty (or there could be a bug in the refactoring code itself).

(I know it's complicated, but there's a reason we've been loud and clear about tree-sitter -- especially non-highlighting features -- being experimental and requiring some basic understanding to use.)
