### ISSUE TITLE
mark os.time as @function.builtin

### ISSUE THREAD

**Issue by YeekongChen** [MunifTanjim/tree-sitter-lua#41]
I just wondering if it is possible to mark all builtin functions as @function.builtin

like highlight os.time() as cyan colour (refers to @function.builtin)
![2804E605-E57D-46AF-AF76-422EB92B4EEE](https://github.com/MunifTanjim/tree-sitter-lua/assets/132744656/fd67aef7-7138-4163-a820-319d786e0aeb)

instead of only mark the builtin namespace (like os) as cyan (refers to @namespace.builtin), and mark the function name as green (refers to @function.call)

![2DFFB2E2-CD69-461D-A75E-BD4623143EC8](https://github.com/MunifTanjim/tree-sitter-lua/assets/132744656/06c015da-d023-4391-9ea3-6e4d66dddd51)

**Comment by MunifTanjim** [comment]
This is possible. You can use a query like this for highlighting:

```scm
(function_call
  (dot_index_expression
    table: (identifier) @namespace.builtin (#any-of? @namespace.builtin "_G" "debug" "io" "jit" "math" "os" "package" "string" "table" "utf8")
    field: (identifier) @function.builtin))
```

**Comment by YeekongChen** [comment]
Thank you very much for the reply!
But actually I wanna go a little bit further, make these things happen on limited functions(listed below), not for all function under the namespace
<details>
  <summary>builtin functions</summary>
  <pre><code>
	"coroutine.create" "coroutine.resume" "coroutine.running" "coroutine.status" "coroutine.wrap" "coroutine.yield"
	"debug.debug" "debug.getfenv" "debug.gethook" "debug.getinfo" "debug.getlocal" "debug.getmetatable" "debug.getregistry"
	"debug.getupvalue" "debug.setfenv" "debug.sethook" "debug.setlocal" "debug.setmetatable" "debug.setupvalue" "debug.traceback"
	"io.close" "io.flush" "io.input" "io.lines" "io.open" "io.output" "io.popen" "io.read"
	"io.tmpfile" "io.type" "io.write"
	"math.abs" "math.acos" "math.asin" "math.atan" "math.atan2" "math.ceil" "math.cos"
	"math.cosh" "math.deg" "math.exp" "math.floor" "math.fmod" "math.frexp" "math.huge"
	"math.ldexp" "math.log" "math.log10" "math.max" "math.min" "math.modf" "math.pi"
	"math.pow" "math.rad" "math.random" "math.randomseed" "math.sin" "math.sinh" "math.sqrt"
	"math.tan" "math.tanh"
	"os.clock" "os.date" "os.difftime" "os.execute" "os.exit" "os.getenv"
	"os.remove" "os.rename" "os.setlocale" "os.time" "os.tmpname"
	"package.cpath" "package.loaded" "package.loadlib" "package.path" "package.preload" "package.seeall"
	"string.byte" "string.char" "string.dump" "string.find" "string.format" "string.gmatch" "string.gsub"
	"string.len" "string.lower" "string.match" "string.rep" "string.reverse" "string.sub" "string.upper"
	"table.concat" "table.insert" "table.maxn" "table.remove" "table.sort"
  </code></pre>
</details>

I have tried some way like:
<details>
  <summary>my test</summary>
  <pre><code>
(function_call
  name: [
	(identifier) @function.call
	(dot_index_expression
	  field: (identifier) @function.call)
	(method_index_expression
	  method: (identifier) @method.call)	
  ]
  (#any-of? @function.builtin
	(identifier) @function.builtin
	"coroutine.create" "coroutine.resume" "coroutine.running" "coroutine.status" "coroutine.wrap" "coroutine.yield"
	"debug.debug" "debug.getfenv" "debug.gethook" "debug.getinfo" "debug.getlocal" "debug.getmetatable" "debug.getregistry"
	.......
  )
)
  </code></pre>
</details>
or
<details>
  <summary>my test</summary>
  <pre><code>
(function_call
  name: (dot_index_expression
    object: (identifier) @namespace
    field: (identifier) @function.builtin)
  (#any-of? @function.builtin
	"coroutine.create" "coroutine.resume" "coroutine.running" "coroutine.status" "coroutine.wrap" "coroutine.yield"
	"debug.debug" "debug.getfenv" "debug.gethook" "debug.getinfo" "debug.getlocal" "debug.getmetatable" "debug.getregistry"
	.......
  )
)
  </code></pre>
</details>
, but it throws errors or doesn't work, as I am not familiar with the syntax here.

I'm looking forward for your reply!

**Comment by MunifTanjim** [comment]
You'll need to do it for each namespace individually, e.g.:

```lua
(function_call
  (dot_index_expression
    table: (identifier) @namespace.builtin (#eq? @namespace.builtin "os")
    field: (identifier) @function.builtin) (#any-of? @function.builtin "exit" "time"))
```

Just to be clear, this is not an issue with the parser.

This discussion is better suited for either https://github.com/tree-sitter or your editor (e.g. https://github.com/nvim-treesitter).

**Comment by YeekongChen** [comment]
For any one who might interest in this feature,
I start a discussion under https://github.com/nvim-treesitter/nvim-treesitter,
and paste my solution which pass my test

here is the link: https://github.com/nvim-treesitter/nvim-treesitter/discussions/5773#discussion-5938401
