### ISSUE TITLE
no lua highlighting

### ISSUE THREAD

**Issue by RunThem** [MunifTanjim/tree-sitter-lua#6]
# no lua highlighting

> OS: Debian GNU/Linux bookworm/sid
> Neovim: v0.6.1([Release](https://github.com/neovim/neovim/releases/download/v0.6.1/nvim-linux64.tar.gz))

In my usual programming languages, only lua has a problem with syntax highlighting. But I can't see what's the problem.

mini config(init.lua)
```lua
require('nvim-treesitter.configs').setup({
        ensure_installed = 'maintained',
        highlight  = { enable = true }
})
```
![image](https://user-images.githubusercontent.com/42234806/158012292-554c1bff-7a7d-4713-ac1b-9e8fab3579e9.png)

**Comment by MunifTanjim** [comment]
You need to open this issue in https://github.com/nvim-treesitter/nvim-treesitter repo. All the highlighting are done by queries in https://github.com/nvim-treesitter/nvim-treesitter.

But from the error message it looks like you need to update the `nvim-treesitter` plugin and reinstall the `lua` parser by doing `:TSInstall lua`.
