### ISSUE TITLE
Update tree-sitter to 0.20

### ISSUE THREAD

**Issue by numToStr** [MunifTanjim/tree-sitter-lua#7]
Hey,

Is it possible to update `tree-sitter` to 0.20? Because running `cargo add tree-sitter` installs 0.20 and it took me a while to figure out that the `tree-sitter-lua` depends on the `tree-sitter` 0.19.

**Comment by MunifTanjim** [comment]
Do I only need to update the version in `Cargo.toml`? 🤔 Or is there something else?
Opened a PR: https://github.com/MunifTanjim/tree-sitter-lua/pull/8

**Comment by numToStr** [comment]
> Do I only need to update the version in `Cargo.toml`?

Yup this is one thing.

> 🤔 Or is there something else?

I am not sure abou that. Maybe rebuild the parser(?)

**Comment by MunifTanjim** [comment]
Published `v0.0.10`

**Comment by numToStr** [comment]
Thanks 👍
